# Generated by Django 3.2.25 on 2025-01-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20250127_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='present',
            old_name='check_out_status',
            new_name='status_in',
        ),
        migrations.RenameField(
            model_name='present',
            old_name='status',
            new_name='status_out',
        ),
    ]
