# Generated by Django 3.2.25 on 2025-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250127_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
