# Generated by Django 3.2.25 on 2025-01-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_present_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='time_in',
        ),
    ]
