# Generated by Django 3.2.25 on 2025-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_present_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='present',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
