# Generated by Django 3.2.25 on 2025-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20250127_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='status_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='present',
            name='status_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
